// Day 23/Project 2/7-angular-spa/src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-contact',
    standalone: true,
    imports: [FormsModule, RouterLink],
    template: `
    <div class="page">
      <h2>📬 Contact Us</h2>
      <p>Send us a message using the form below!</p>
      
      <div class="card">
        <h3>Send a Message</h3>
        <form (ngSubmit)="submitForm()">
          <input 
            type="text" 
            placeholder="Your Name" 
            [(ngModel)]="formData.name"
            name="name"
            required 
          />
          <input 
            type="email" 
            placeholder="Your Email" 
            [(ngModel)]="formData.email"
            name="email"
            required 
          />
          <textarea 
            rows="5" 
            placeholder="Your Message"
            [(ngModel)]="formData.message"
            name="message"
            required 
          ></textarea>
          <button type="submit" class="btn">Send Message</button>
        </form>
      </div>
      
      <a routerLink="/" class="btn">← Back Home</a>
    </div>
  `,
    styles: []
})
export class ContactComponent {
    formData = {
        name: '',
        email: '',
        message: ''
    };

    submitForm(): void {
        alert('Message sent! (Demo only)');
        this.formData = { name: '', email: '', message: '' };
    }
}

// Day 23/Project 2/8-vue-init/src/views/Contact.vue
<template>
  <div class="page">
    <h2>📬 Contact Us</h2>
    <p>Send us a message using the form below!</p>
    
    <div class="card">
      <h3>Send a Message</h3>
      <form @submit.prevent="submitForm">
        <input 
          type="text" 
          placeholder="Your Name" 
          v-model="formData.name"
          required 
        />
        <input 
          type="email" 
          placeholder="Your Email" 
          v-model="formData.email"
          required 
        />
        <textarea 
          rows="5" 
          placeholder="Your Message"
          v-model="formData.message"
          required 
        ></textarea>
        <button type="submit" class="btn">Send Message</button>
      </form>
    </div>
    
    <router-link to="/" class="btn">← Back Home</router-link>
  </div>
</template>

<script setup>
import { reactive } from 'vue'

const formData = reactive({
  name: '',
  email: '',
  message: ''
})

const submitForm = () => {
  alert('Message sent! (Demo only)')
  formData.name = ''
  formData.email = ''
  formData.message = ''
}
</script>
