// Day 23/Project 2/8-vue-init/src/App.vue
<template>
  <div id="app">
    <header>
      <h1>💚 Vue SPA</h1>
      <nav>
        <router-link to="/">Home</router-link>
        <router-link to="/about">About</router-link>
        <router-link to="/contact">Contact</router-link>
      </nav>
    </header>
    <main>
      <router-view v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
    </main>
    <footer>
      <p>© 2024 Vue SPA Template - Built with Vue 3</p>
    </footer>
  </div>
</template>

<script setup>
// Vue 3 Composition API
</script>

<style scoped>
nav a.router-link-active {
  background: rgba(255,255,255,0.25);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// Day 23/Project 2/7-angular-spa/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
    selector: 'app-root',
    standalone: true,
    imports: [RouterOutlet, RouterLink, RouterLinkActive],
    template: `
    <div id="app">
      <header>
        <h1>🅰️ Angular SPA</h1>
        <nav>
          <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a>
          <a routerLink="/about" routerLinkActive="active">About</a>
          <a routerLink="/contact" routerLinkActive="active">Contact</a>
        </nav>
      </header>
      <main>
        <router-outlet></router-outlet>
      </main>
      <footer>
        <p>© 2024 Angular SPA Template - Built with Angular {{ angularVersion }}</p>
      </footer>
    </div>
  `,
    styles: []
})
export class AppComponent {
    angularVersion = '17';
}
