// Day 23/Project 2/7-angular-spa/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
    selector: 'app-root',
    standalone: true,
    imports: [RouterOutlet, RouterLink, RouterLinkActive],
    template: `
    <div id="app">
      <header>
        <h1>🅰️ Angular SPA</h1>
        <nav>
          <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a>
          <a routerLink="/about" routerLinkActive="active">About</a>
          <a routerLink="/contact" routerLinkActive="active">Contact</a>
        </nav>
      </header>
      <main>
        <router-outlet></router-outlet>
      </main>
      <footer>
        <p>© 2024 Angular SPA Template - Built with Angular {{ angularVersion }}</p>
      </footer>
    </div>
  `,
    styles: []
})
export class AppComponent {
    angularVersion = '17';
}

// Day 23/Project 2/5-vite-vue/src/App.vue
<template>
  <div id="app">
    <header>
      <h1>💚 Vite Vue SPA</h1>
      <nav>
        <router-link to="/">Home</router-link>
        <router-link to="/about">About</router-link>
        <router-link to="/contact">Contact</router-link>
      </nav>
    </header>
    <main>
      <router-view v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
    </main>
    <footer>
      <p>© 2024 Vite Vue Template - Powered by Vue 3 & Vite</p>
    </footer>
  </div>
</template>

<script setup>
import './style.css'
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
