// Day 23/Project 2/8-vue-init/src/views/Home.vue
<template>
  <div class="page">
    <h2>🏠 Welcome Home</h2>
    <p>Welcome to the Vue 3 Single Page Application!</p>
    
    <div class="card">
      <h3>Vue 3 Features</h3>
      <ul>
        <li>⚡ Composition API</li>
        <li>🎯 Improved TypeScript support</li>
        <li>📦 Smaller bundle size</li>
        <li>🚀 Faster rendering</li>
        <li>💚 Simpler state management</li>
      </ul>
    </div>
    
    <div class="card">
      <h3>Vue Router Features</h3>
      <ul>
        <li>🔗 Nested routes</li>
        <li>📍 History mode</li>
        <li>🔄 Route guards</li>
        <li>📱 Lazy loading</li>
      </ul>
    </div>
    
    <router-link to="/about" class="btn">Learn More →</router-link>
    <router-link to="/contact" class="btn">Contact Us</router-link>
  </div>
</template>

<script setup>
// Vue 3 Composition API - Home Component
</script>

// Day 23/Project 2/7-angular-spa/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-home',
    standalone: true,
    imports: [RouterLink],
    template: `
    <div class="page">
      <h2>🏠 Welcome Home</h2>
      <p>Welcome to the Angular Single Page Application!</p>
      
      <div class="card">
        <h3>Angular Features</h3>
        <ul>
          <li>✓ TypeScript-based</li>
          <li>✓ Dependency Injection</li>
          <li>✓ Two-way data binding</li>
          <li>✓ Modular architecture</li>
          <li>✓ Enterprise-ready</li>
        </ul>
      </div>
      
      <div class="card">
        <h3>Angular 17 Features</h3>
        <ul>
          <li>🚀 Standalone components by default</li>
          <li>⚡ Improved hydration</li>
          <li>🎯 Deferrable views</li>
          <li>📦 Reduced bundle size</li>
        </ul>
      </div>
      
      <a routerLink="/about" class="btn">Learn More →</a>
      <a routerLink="/contact" class="btn">Contact Us</a>
    </div>
  `,
    styles: []
})
export class HomeComponent { }
